endereco:
    path:     /
    defaults: { _controller: "FinanceiroBundle:Endereco:index" }

endereco_show:
    path:     /{id}/show
    defaults: { _controller: "FinanceiroBundle:Endereco:show" }

endereco_new:
    path:     /new
    defaults: { _controller: "FinanceiroBundle:Endereco:new" }

endereco_create:
    path:     /create
    defaults: { _controller: "FinanceiroBundle:Endereco:create" }
    methods:  POST

endereco_edit:
    path:     /{id}/edit
    defaults: { _controller: "FinanceiroBundle:Endereco:edit" }

endereco_update:
    path:     /{id}/update
    defaults: { _controller: "FinanceiroBundle:Endereco:update" }
    methods:  [POST, PUT]

endereco_delete:
    path:     /{id}/delete
    defaults: { _controller: "FinanceiroBundle:Endereco:delete" }
    methods:  [POST, DELETE]
