os:
    path:     /
    defaults: { _controller: "FinanceiroBundle:Os:index" }

os_show:
    path:     /{id}/show
    defaults: { _controller: "FinanceiroBundle:Os:show" }

os_new:
    path:     /new
    defaults: { _controller: "FinanceiroBundle:Os:new" }

os_create:
    path:     /create
    defaults: { _controller: "FinanceiroBundle:Os:create" }
    methods:  POST

os_edit:
    path:     /{id}/edit
    defaults: { _controller: "FinanceiroBundle:Os:edit" }

os_update:
    path:     /{id}/update
    defaults: { _controller: "FinanceiroBundle:Os:update" }
    methods:  [POST, PUT]

os_delete:
    path:     /{id}/delete
    defaults: { _controller: "FinanceiroBundle:Os:delete" }
    methods:  [POST, DELETE]
