oshasitem:
    path:     /
    defaults: { _controller: "FinanceiroBundle:OsHasItem:index" }

oshasitem_show:
    path:     /{id}/show
    defaults: { _controller: "FinanceiroBundle:OsHasItem:show" }

oshasitem_new:
    path:     /new
    defaults: { _controller: "FinanceiroBundle:OsHasItem:new" }

oshasitem_create:
    path:     /create
    defaults: { _controller: "FinanceiroBundle:OsHasItem:create" }
    methods:  POST

oshasitem_edit:
    path:     /{id}/edit
    defaults: { _controller: "FinanceiroBundle:OsHasItem:edit" }

oshasitem_update:
    path:     /{id}/update
    defaults: { _controller: "FinanceiroBundle:OsHasItem:update" }
    methods:  [POST, PUT]

oshasitem_delete:
    path:     /{id}/delete
    defaults: { _controller: "FinanceiroBundle:OsHasItem:delete" }
    methods:  [POST, DELETE]
