pais:
    path:     /
    defaults: { _controller: "FinanceiroBundle:Pais:index" }

pais_show:
    path:     /{id}/show
    defaults: { _controller: "FinanceiroBundle:Pais:show" }

pais_new:
    path:     /new
    defaults: { _controller: "FinanceiroBundle:Pais:new" }

pais_create:
    path:     /create
    defaults: { _controller: "FinanceiroBundle:Pais:create" }
    methods:  POST

pais_edit:
    path:     /{id}/edit
    defaults: { _controller: "FinanceiroBundle:Pais:edit" }

pais_update:
    path:     /{id}/update
    defaults: { _controller: "FinanceiroBundle:Pais:update" }
    methods:  [POST, PUT]

pais_delete:
    path:     /{id}/delete
    defaults: { _controller: "FinanceiroBundle:Pais:delete" }
    methods:  [POST, DELETE]
