tipocobrancapagamento:
    path:     /
    defaults: { _controller: "FinanceiroBundle:TipoCobrancaPagamento:index" }

tipocobrancapagamento_show:
    path:     /{id}/show
    defaults: { _controller: "FinanceiroBundle:TipoCobrancaPagamento:show" }

tipocobrancapagamento_new:
    path:     /new
    defaults: { _controller: "FinanceiroBundle:TipoCobrancaPagamento:new" }

tipocobrancapagamento_create:
    path:     /create
    defaults: { _controller: "FinanceiroBundle:TipoCobrancaPagamento:create" }
    methods:  POST

tipocobrancapagamento_edit:
    path:     /{id}/edit
    defaults: { _controller: "FinanceiroBundle:TipoCobrancaPagamento:edit" }

tipocobrancapagamento_update:
    path:     /{id}/update
    defaults: { _controller: "FinanceiroBundle:TipoCobrancaPagamento:update" }
    methods:  [POST, PUT]

tipocobrancapagamento_delete:
    path:     /{id}/delete
    defaults: { _controller: "FinanceiroBundle:TipoCobrancaPagamento:delete" }
    methods:  [POST, DELETE]
