Cliente:
    type: entity
    table: cliente
    indexes:
        idx_1:
            columns:
                - celular
                - email
                - telefone
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        telefone:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        celular:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        status:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        tipo:
            type: string
            nullable: false
            length: 3
            fixed: false
            comment: ''
            default: PJ
        observacao:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        created:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
