Endereco:
    type: entity
    table: endereco
    indexes:
        fk_endereco_lav_clientes1_idx:
            columns:
                - cliente_id
        fk_endereco_lav_cidades1_idx:
            columns:
                - cidade_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        rua:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        bairro:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        numero:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        complemento:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        cep:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        tipo:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        cidade:
            targetEntity: Cidade
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cidade_id:
                    referencedColumnName: id
            orphanRemoval: false
        cliente:
            targetEntity: Cliente
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cliente_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
