Item:
    type: entity
    table: item
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        item:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: "\n"
    lifecycleCallbacks: {  }
