Pedido:
    type: entity
    table: pedido
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dataPedido:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: data_pedido
    lifecycleCallbacks: {  }
