PedidoHasFornecedorHasInsumo:
    type: entity
    table: pedido_has_fornecedor_has_insumo
    indexes:
        fk_pedidos_has_fornecedores_has_insumos_fornecedores_has_in_idx:
            columns:
                - fornecedor_has_insumo_id
        fk_pedidos_has_fornecedores_has_insumos_pedidos1_idx:
            columns:
                - pedidos_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        valorPraticado:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: valor_praticado
        qtd:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    manyToOne:
        fornecedorHasInsumo:
            targetEntity: FornecedorHasInsumo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fornecedor_has_insumo_id:
                    referencedColumnName: id
            orphanRemoval: false
        pedidos:
            targetEntity: Pedido
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                pedidos_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
