TipoCobrancaPagamento:
    type: entity
    table: tipo_cobranca_pagamento
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tipoCobrancaPagamento:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: tipo_cobranca_pagamento
    lifecycleCallbacks: {  }
